name: Run Unity Tests
# Reference https://game.ci/docs/github/getting-started for future changes.

on:
  pull_request:
    branches:
      - setup-automated-tests
  workflow_dispatch: 

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: 
          - Unity/com.chopsticks.dependencies  # Add future package projects here.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: ${{ matrix.project }}/Library
          key: Library-${{ matrix.project }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.project }}-

      - name: Run Play Mode Tests for ${{ matrix.project }}
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Test Results for ${{ matrix.project }}
        uses: actions/upload-artifact@v4
        with:
          name: TestResults-${{ matrix.project }}
          path: ${{ matrix.project }}/artifacts